// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqpmQLggK0-TTm8qjb_eRqU_QcT0KMuxo',
    appId: '1:590690634548:web:e9740240502ca8ced4b361',
    messagingSenderId: '590690634548',
    projectId: 'lodolist',
    authDomain: 'lodolist.firebaseapp.com',
    storageBucket: 'lodolist.appspot.com',
    measurementId: 'G-DCWZSRH81S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxJMaMCs5OyitreIfXFHR8VrmrdI_Rx24',
    appId: '1:590690634548:android:431a713274b13410d4b361',
    messagingSenderId: '590690634548',
    projectId: 'lodolist',
    storageBucket: 'lodolist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLvunExJIi1w8D39hDrYqeNJP-DPMlrTw',
    appId: '1:590690634548:ios:95eff0f9a8f22132d4b361',
    messagingSenderId: '590690634548',
    projectId: 'lodolist',
    storageBucket: 'lodolist.appspot.com',
    iosClientId: '590690634548-s8d5f1vs2v1ui5cap4n99dks4g0tns67.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLvunExJIi1w8D39hDrYqeNJP-DPMlrTw',
    appId: '1:590690634548:ios:fcf772562f0839c0d4b361',
    messagingSenderId: '590690634548',
    projectId: 'lodolist',
    storageBucket: 'lodolist.appspot.com',
    iosClientId: '590690634548-trpo4o1hi8qrt3gpb9krfce7g9vsgj5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
